apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote
spec:
  selector:
    
  template:
    metadata:
      name: vote
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80
              name: vote